### ISSUE TITLE
update

### ISSUE THREAD

**Issue by squirdsmacintosh** [giacomoferretti/CloudflareScraper#2]
hi, is it possible that you update your scraper?

**Comment by giacomoferretti** [comment]
Yes, I could update the scraper, but I don't have much time in this period. I will update you when I will start working on it.

**Comment by giacomoferretti** [comment]
I've tried updating the code, but the included Nashorn engine doesn't support some functions added in the Cloudflare challenge. We could use either Node JS or something else, but I won't update the code in the near future.
