### ISSUE TITLE
Is this still active? 

### ISSUE THREAD

**Issue by MrIvanPlays** [giacomoferretti/CloudflareScraper#3]
I need a working cloudflare scraper for java, but I can't find a working one. If you know what I should change in your code, please let me know I will PR it. I need that thing

**Comment by giacomoferretti** [comment]
I've recently unarchived this repository. I have a working code ready thanks to "Free HongKong". I will fix the repo soon. Stay tuned!

**Comment by MrIvanPlays** [comment]
> I've recently unarchived this repository. I have a working code ready thanks to "Free HongKong". I will fix the repo soon. Stay tuned!

Very nice :)

**Comment by MrIvanPlays** [comment]
When will that code be pushed for use ?

**Comment by giacomoferretti** [comment]
As soon as possible

**Comment by MrIvanPlays** [comment]
> As soon as possible

Is there any ETA on that statement?

**Comment by giacomoferretti** [comment]
I've tried updating the code, but the included Nashorn engine doesn't support some functions added in the Cloudflare challenge. We could use either Node JS or something else, but I won't update the code in the near future.

**Comment by MrIvanPlays** [comment]
Change the nashorn engine with something other I guess?

EDIT: Or maybe update it if it's not latest version
